### ISSUE TITLE
How to get skipoffset in Linear (vast).

### ISSUE THREAD

**Issue by dainv123** [cinema6/vast-player#11]
Help me. Thanks!!!
How to get **skipoffset** in **Linear**. 

![capture](https://user-images.githubusercontent.com/35486233/35434979-9da2b4c2-02bb-11e8-8998-9993cfe61362.PNG)

**Comment by minznerjosh** [comment]
Can you please send a jsfiddle with a `VASTPlayer` that is loading an ad with a `skipoffset`? Thanks!

**Comment by skaflock** [comment]
Hi!
I have same problem.
Here is XML I'm trying to load:
https://drive.google.com/open?id=14-tz3VkpO7VQeG0YGma2fUlTpKE38hS3


How can i get skipoffset attribute value ?
