### ISSUE TITLE
VAST 4.0 supported soon?

### ISSUE THREAD

**Issue by xblabs** [cinema6/vast-player#12]
Hi and thanks for the great library. Do you plan to support VAST 4.0 anytime soon?

**Comment by xblabs** [comment]
Hi, any info on the above? Many thanks!

**Comment by xblabs** [comment]
Hi Josh, any updates on that? Would be really awesome to know your plans on VAST4 and if you need help with anything.

**Comment by minznerjosh** [comment]
Closing in favor of minznerjosh/vastacular#19.
