### ISSUE TITLE
Hot to set withCredentials on xhr object?

### ISSUE THREAD

**Issue by dmitry-dedukhin** [cinema6/vast-player#2]
Hi!

Seems there is no any possibility to send cookies when requesting vast link?

**Comment by minznerjosh** [comment]
Hello!

Requests are made by `vastacular` on this line: https://github.com/cinema6/vastacular/blob/master/lib/VAST.js#L440

I will gladly accept a PR that adds support for sending cookies. Cheers! 🍻
