### ISSUE TITLE
error...

### ISSUE THREAD

**Issue by qwill** [cinema6/vast-player#3]
Uncaught ReferenceError: require is not defined
    at VASTPlayer.js:3

**Comment by minznerjosh** [comment]
Hello and sorry for the delay! You either need to use browserify to build the package, OR use one of the prebuilt hosted scripts:

```html
<script src="https://cdn.jsdelivr.net/vast-player/0.2/vast-player.min.js"></script>
```

You could also build the script yourself by cloning the repo and running

```bash
$> npm install && npm run build
```
