### ISSUE TITLE
Scrollbars won't go away

### ISSUE THREAD

**Issue by notmark** [cinema6/vast-player#9]
Any idea why this is happening on all browsers? I've tried every css trick I can think of and nothing is working.

Here's a screenshot of the issue: http://prntscr.com/his7ty

**Comment by minznerjosh** [comment]
Can you post a jsfiddle with the issue?

**Comment by notmark** [comment]
https://jsfiddle.net/notmark/q3fL9dok/3/

**Comment by notmark** [comment]
I figured it out. I added scrolling="no" to the container iframe.
